version: "2"

linters:
    settings:
        errcheck:
            exclude-functions:
                - (io.Closer).Close
        exhaustruct:
            exclude:
                - 'crypto/tls\.Config'
                - 'github\.com/redis/go-redis/v9\.Options'
