// Code generated by MockGen. DO NOT EDIT.
// Source: task_queue.go
//
// Generated by this command:
//
//	mockgen -source=task_queue.go -destination=mock.go -package=taskqueue
//

// Package taskqueue is a generated GoMock package.
package taskqueue

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskQueue is a mock of TaskQueue interface.
type MockTaskQueue struct {
	ctrl     *gomock.Controller
	recorder *MockTaskQueueMockRecorder
	isgomock struct{}
}

// MockTaskQueueMockRecorder is the mock recorder for MockTaskQueue.
type MockTaskQueueMockRecorder struct {
	mock *MockTaskQueue
}

// NewMockTaskQueue creates a new mock instance.
func NewMockTaskQueue(ctrl *gomock.Controller) *MockTaskQueue {
	mock := &MockTaskQueue{ctrl: ctrl}
	mock.recorder = &MockTaskQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskQueue) EXPECT() *MockTaskQueueMockRecorder {
	return m.recorder
}

// DeleteTask mocks base method.
func (m *MockTaskQueue) DeleteTask(ctx context.Context, taskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskQueueMockRecorder) DeleteTask(ctx, taskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskQueue)(nil).DeleteTask), ctx, taskID)
}

// RegisterNotification mocks base method.
func (m *MockTaskQueue) RegisterNotification(ctx context.Context, task *NotificationTask) (*TaskResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterNotification", ctx, task)
	ret0, _ := ret[0].(*TaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterNotification indicates an expected call of RegisterNotification.
func (mr *MockTaskQueueMockRecorder) RegisterNotification(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNotification", reflect.TypeOf((*MockTaskQueue)(nil).RegisterNotification), ctx, task)
}
