// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock.go -package=timemgmt
//

// Package timemgmt is a generated GoMock package.
package timemgmt

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRemindTimeRepository is a mock of RemindTimeRepository interface.
type MockRemindTimeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRemindTimeRepositoryMockRecorder
	isgomock struct{}
}

// MockRemindTimeRepositoryMockRecorder is the mock recorder for MockRemindTimeRepository.
type MockRemindTimeRepositoryMockRecorder struct {
	mock *MockRemindTimeRepository
}

// NewMockRemindTimeRepository creates a new mock instance.
func NewMockRemindTimeRepository(ctrl *gomock.Controller) *MockRemindTimeRepository {
	mock := &MockRemindTimeRepository{ctrl: ctrl}
	mock.recorder = &MockRemindTimeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemindTimeRepository) EXPECT() *MockRemindTimeRepositoryMockRecorder {
	return m.recorder
}

// GetRemindsByTimeRange mocks base method.
func (m *MockRemindTimeRepository) GetRemindsByTimeRange(ctx context.Context, start, end time.Time) (*RemindsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemindsByTimeRange", ctx, start, end)
	ret0, _ := ret[0].(*RemindsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemindsByTimeRange indicates an expected call of GetRemindsByTimeRange.
func (mr *MockRemindTimeRepositoryMockRecorder) GetRemindsByTimeRange(ctx, start, end any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemindsByTimeRange", reflect.TypeOf((*MockRemindTimeRepository)(nil).GetRemindsByTimeRange), ctx, start, end)
}

// UpdateThrottled mocks base method.
func (m *MockRemindTimeRepository) UpdateThrottled(ctx context.Context, id string, throttled bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThrottled", ctx, id, throttled)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThrottled indicates an expected call of UpdateThrottled.
func (mr *MockRemindTimeRepositoryMockRecorder) UpdateThrottled(ctx, id, throttled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThrottled", reflect.TypeOf((*MockRemindTimeRepository)(nil).UpdateThrottled), ctx, id, throttled)
}
