// Code generated by MockGen. DO NOT EDIT.
// Source: throttle_repository.go
//
// Generated by this command:
//
//	mockgen -source=throttle_repository.go -destination=throttle_repository_mock.go -package=domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockThrottleRepository is a mock of ThrottleRepository interface.
type MockThrottleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThrottleRepositoryMockRecorder
	isgomock struct{}
}

// MockThrottleRepositoryMockRecorder is the mock recorder for MockThrottleRepository.
type MockThrottleRepositoryMockRecorder struct {
	mock *MockThrottleRepository
}

// NewMockThrottleRepository creates a new mock instance.
func NewMockThrottleRepository(ctrl *gomock.Controller) *MockThrottleRepository {
	mock := &MockThrottleRepository{ctrl: ctrl}
	mock.recorder = &MockThrottleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThrottleRepository) EXPECT() *MockThrottleRepositoryMockRecorder {
	return m.recorder
}

// DeletePlan mocks base method.
func (m *MockThrottleRepository) DeletePlan(ctx context.Context, minuteKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlan", ctx, minuteKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlan indicates an expected call of DeletePlan.
func (mr *MockThrottleRepositoryMockRecorder) DeletePlan(ctx, minuteKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlan", reflect.TypeOf((*MockThrottleRepository)(nil).DeletePlan), ctx, minuteKey)
}

// GetCommittedPacket mocks base method.
func (m *MockThrottleRepository) GetCommittedPacket(ctx context.Context, remindID string) (*Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommittedPacket", ctx, remindID)
	ret0, _ := ret[0].(*Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommittedPacket indicates an expected call of GetCommittedPacket.
func (mr *MockThrottleRepositoryMockRecorder) GetCommittedPacket(ctx, remindID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommittedPacket", reflect.TypeOf((*MockThrottleRepository)(nil).GetCommittedPacket), ctx, remindID)
}

// GetPacketCountForMinute mocks base method.
func (m *MockThrottleRepository) GetPacketCountForMinute(ctx context.Context, minuteKey string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPacketCountForMinute", ctx, minuteKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPacketCountForMinute indicates an expected call of GetPacketCountForMinute.
func (mr *MockThrottleRepositoryMockRecorder) GetPacketCountForMinute(ctx, minuteKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPacketCountForMinute", reflect.TypeOf((*MockThrottleRepository)(nil).GetPacketCountForMinute), ctx, minuteKey)
}

// GetPlan mocks base method.
func (m *MockThrottleRepository) GetPlan(ctx context.Context, minuteKey string) (*Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlan", ctx, minuteKey)
	ret0, _ := ret[0].(*Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlan indicates an expected call of GetPlan.
func (mr *MockThrottleRepositoryMockRecorder) GetPlan(ctx, minuteKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlan", reflect.TypeOf((*MockThrottleRepository)(nil).GetPlan), ctx, minuteKey)
}

// GetPlannedPacket mocks base method.
func (m *MockThrottleRepository) GetPlannedPacket(ctx context.Context, remindID string) (*PlannedPacket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlannedPacket", ctx, remindID)
	ret0, _ := ret[0].(*PlannedPacket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlannedPacket indicates an expected call of GetPlannedPacket.
func (mr *MockThrottleRepositoryMockRecorder) GetPlannedPacket(ctx, remindID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlannedPacket", reflect.TypeOf((*MockThrottleRepository)(nil).GetPlannedPacket), ctx, remindID)
}

// GetPlannedPacketCount mocks base method.
func (m *MockThrottleRepository) GetPlannedPacketCount(ctx context.Context, minuteKey string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlannedPacketCount", ctx, minuteKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlannedPacketCount indicates an expected call of GetPlannedPacketCount.
func (mr *MockThrottleRepositoryMockRecorder) GetPlannedPacketCount(ctx, minuteKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlannedPacketCount", reflect.TypeOf((*MockThrottleRepository)(nil).GetPlannedPacketCount), ctx, minuteKey)
}

// GetPlansInRange mocks base method.
func (m *MockThrottleRepository) GetPlansInRange(ctx context.Context, startMinuteKey, endMinuteKey string) ([]*Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlansInRange", ctx, startMinuteKey, endMinuteKey)
	ret0, _ := ret[0].([]*Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlansInRange indicates an expected call of GetPlansInRange.
func (mr *MockThrottleRepositoryMockRecorder) GetPlansInRange(ctx, startMinuteKey, endMinuteKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlansInRange", reflect.TypeOf((*MockThrottleRepository)(nil).GetPlansInRange), ctx, startMinuteKey, endMinuteKey)
}

// IncrementPacketCount mocks base method.
func (m *MockThrottleRepository) IncrementPacketCount(ctx context.Context, minuteKey string, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementPacketCount", ctx, minuteKey, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementPacketCount indicates an expected call of IncrementPacketCount.
func (mr *MockThrottleRepositoryMockRecorder) IncrementPacketCount(ctx, minuteKey, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementPacketCount", reflect.TypeOf((*MockThrottleRepository)(nil).IncrementPacketCount), ctx, minuteKey, delta)
}

// IsPacketCommitted mocks base method.
func (m *MockThrottleRepository) IsPacketCommitted(ctx context.Context, remindID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPacketCommitted", ctx, remindID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPacketCommitted indicates an expected call of IsPacketCommitted.
func (mr *MockThrottleRepositoryMockRecorder) IsPacketCommitted(ctx, remindID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPacketCommitted", reflect.TypeOf((*MockThrottleRepository)(nil).IsPacketCommitted), ctx, remindID)
}

// SaveCommittedPacket mocks base method.
func (m *MockThrottleRepository) SaveCommittedPacket(ctx context.Context, packet *Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommittedPacket", ctx, packet)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommittedPacket indicates an expected call of SaveCommittedPacket.
func (mr *MockThrottleRepositoryMockRecorder) SaveCommittedPacket(ctx, packet any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommittedPacket", reflect.TypeOf((*MockThrottleRepository)(nil).SaveCommittedPacket), ctx, packet)
}

// SavePlan mocks base method.
func (m *MockThrottleRepository) SavePlan(ctx context.Context, plan *Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePlan", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePlan indicates an expected call of SavePlan.
func (mr *MockThrottleRepositoryMockRecorder) SavePlan(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePlan", reflect.TypeOf((*MockThrottleRepository)(nil).SavePlan), ctx, plan)
}
